# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=32, verbose_name='ip\u5730\u5740')),
                ('address', models.CharField(default='', max_length=32, verbose_name='\u5730\u5740')),
                ('access_time', models.CharField(default='', max_length=32, verbose_name='\u8bbf\u95ee\u65f6\u95f4')),
                ('source', models.CharField(default='', max_length=500, verbose_name='\u6765\u6e90')),
                ('keywords', models.CharField(default='', max_length=100, verbose_name='\u641c\u7d22\u8bcd')),
                ('is_sem', models.CharField(choices=[('yes', '\u662f'), ('no', '\u5426')], max_length=5, verbose_name='\u662f\u5426\u63a8\u5e7f')),
            ],
            options={
                'verbose_name': '\u7edf\u8ba1\u8868',
                'verbose_name_plural': '\u7edf\u8ba1\u8868',
            },
        ),
    ]
