# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20170329_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='is_sem',
            field=models.CharField(choices=[('yes', '\u662f'), ('no', '\u5426')], default='no', max_length=5, verbose_name='\u662f\u5426\u63a8\u5e7f'),
        ),
    ]
