# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20170329_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='access_isp',
            field=models.CharField(default='', max_length=50, verbose_name='\u8fd0\u8425\u5546'),
        ),
        migrations.AddField(
            model_name='show',
            name='access_os',
            field=models.CharField(default='', max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf'),
        ),
        migrations.AddField(
            model_name='show',
            name='access_page',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bbf\u95ee\u9875\u9762'),
        ),
        migrations.AddField(
            model_name='show',
            name='access_screen',
            field=models.CharField(default='', max_length=100, verbose_name='\u5c4f\u5e55\u5206\u8fa8\u7387'),
        ),
        migrations.AddField(
            model_name='show',
            name='entrance',
            field=models.CharField(default='', max_length=1000, verbose_name='\u5165\u53e3\u9875\u9762'),
        ),
        migrations.AddField(
            model_name='show',
            name='last_page',
            field=models.CharField(default='', max_length=1000, verbose_name='\u6700\u540e\u505c\u7559'),
        ),
        migrations.AddField(
            model_name='show',
            name='last_time',
            field=models.CharField(default='', max_length=100, verbose_name='\u4e0a\u4e00\u6b21\u8bbf\u95ee'),
        ),
        migrations.AddField(
            model_name='show',
            name='page_total',
            field=models.IntegerField(default=1, max_length=10, verbose_name='\u9875\u9762\u6570'),
        ),
        migrations.AddField(
            model_name='show',
            name='user_type',
            field=models.CharField(choices=[('new', '\u65b0\u7528\u6237'), ('old', '\u8001\u7528\u6237')], default='new', max_length=3, verbose_name='\u7528\u6237\u7c7b\u578b'),
        ),
    ]
